// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD30fTEvix4s8_a3rlu0apUiFtmI0zgFWw',
    appId: '1:109275156915:web:073081653f5e1edf4c7bc6',
    messagingSenderId: '109275156915',
    projectId: 'reddit-cf4b2',
    authDomain: 'reddit-cf4b2.firebaseapp.com',
    storageBucket: 'reddit-cf4b2.appspot.com',
    measurementId: 'G-1TWBY9BMMV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBp6FTw3vlWskYUodQUAmjS23kVZ_yF8IA',
    appId: '1:109275156915:android:b862d10ed9fcde184c7bc6',
    messagingSenderId: '109275156915',
    projectId: 'reddit-cf4b2',
    storageBucket: 'reddit-cf4b2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtoXpNeaUeS8Je93RVmJy8bhwQqCTUQ6s',
    appId: '1:109275156915:ios:785edc1ed5e100614c7bc6',
    messagingSenderId: '109275156915',
    projectId: 'reddit-cf4b2',
    storageBucket: 'reddit-cf4b2.appspot.com',
    iosBundleId: 'com.example.reddit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtoXpNeaUeS8Je93RVmJy8bhwQqCTUQ6s',
    appId: '1:109275156915:ios:39a5cd031e4215764c7bc6',
    messagingSenderId: '109275156915',
    projectId: 'reddit-cf4b2',
    storageBucket: 'reddit-cf4b2.appspot.com',
    iosBundleId: 'com.example.reddit.RunnerTests',
  );
}
